default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: your_new_password
  host: localhost

development:
  <<: *default
  url: "postgresql://planet_kvzq_user:akhyv0FAnGYDA7mo7210v9qm6LqxDWkI@dpg-cqlojmjv2p9s73b9g710-a.oregon-postgres.render.com/planet_kvzq"

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  url: "postgresql://planet_kvzq_user:akhyv0FAnGYDA7mo7210v9qm6LqxDWkI@dpg-cqlojmjv2p9s73b9g710-a.oregon-postgres.render.com/planet_kvzq"
